# Generated by Django 5.1 on 2024-09-11 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channel_app", "0001_initial"),
        ("users", "0002_alter_profile_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmessage",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.profile"
            ),
        ),
    ]
